### ISSUE TITLE
No reading off 

### ISSUE THREAD

**Issue by holgerble** [iobroker-community-adapters/ioBroker.systeminfo#139]
Since the last update of the systeminfo adapter, the system values are no longer read out or entered in the adapter's object list.
Even after installing a second systeminfo adapter, no more objects are created.
It is a Raspi 4, everything is up to date.
Iobroker, node-js and npm are the latest version recommended for PI 4.
Does anyone have a tip for me?

Last protokoll
2023-09-28 17:54:00.012  - debug: systeminfo.1 (20550) Aussentemp  received '21.2'
2023-09-28 17:54:00.014  - debug: systeminfo.1 (20550) MS TypeError: this._extendObject is not a function    at MyAdapter.extendObject (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:2051:21)    at /opt/iobroker/node_modules/iobroker.systeminfo/myAdapter.js:431:96    at new Promise (<anonymous>)    at MyAdapter.extendObject (/opt/iobroker/node_modules/iobroker.systeminfo/myAdapter.js:430:20)    at MyAdapter.makeState (/opt/iobroker/node_modules/iobroker.systeminfo/myAdapter.js:667:21)    at setItem (/opt/iobroker/node_modules/iobroker.systeminfo/systeminfo.js:467:14)    at /opt/iobroker/node_modules/iobroker.systeminfo/systeminfo.js:594:58    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by mcm1957** [comment]
Please add version information:

adapter:
js-controller:
admin:
node:
O/S:

**Comment by holgerble** [comment]
system-info   1.1.0
js-controller  5.0.12
admin  6.10.1
node  18.18.0
Raspi 4 with 4 gb  
OK:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
OK:3 http://giteduberger.fr rpimonitor/ InRelease
OK:4 https://apt.grafana.com stable InRelease
OK:5 https://deb.nodesource.com/node_18.x nodistro InRelease
OK:6 https://repos.influxdata.com/debian stable InRelease

**Comment by holgerble** [comment]
No tip for me ???
Adapter worked for several years..
Start is locking o.k... found several items...
but NO OBJECTS ARE CREATED !!!
***********************************
systeminfo.1 | 2023-10-01 16:05:48.871 | info | Adapter systeminfo.1 started and found 14/109 items/states to process.
-- | -- | -- | --
systeminfo.1 | 2023-10-01 16:05:38.330 | info | Startup Systeminfo Adapter systeminfo.1: { startup: '#\n' + '#gpio mode 1 output\n' + '#rpi: echo none >/sys/class/leds/led0/trigger\n' + '#echo none >/sys/class/leds/green_led/trigger', items: [ { name: 'System.Temperature', type: 'file', source: '/sys/class/thermal/thermal_zone0/temp', regexp: '', conv: 'number', role: 'value.temperature\|°C', write: '', sched: '*:/2' }, { name: '-System.Memory_[used, free, available]', type: 'exec', source: 'free -k', regexp: 'Mem\\:\\s+\\d+\\s+(\\d+)\\s+(\\d+)\\s+\\d+\\s+\\d+\\s+(\\d+)', conv: '@/1000', role: 'number\|MB', write: '', sched: '1 * * * * ' }, { name: '-TestSystem.processes.[command/pcpu]', type: 'info', source: 'processes', regexp: "list[?(@.user == 'pi')]", conv: '', role: '', write: '', sched: '*:2' }, { name: '-XS2.[name/value]', type: 'web', source: "http://xs1/control.html'", regexp: `{"l[?(@.value !== null )]": {"l[tr]": { '![@.children()]':0, name: {_eq:1}, value: {_eq:2, _conv:"parseInt(@.slice(0,-1))"}}, _filter: ($) => $[0].childNodes.length==3}}`, conv: 'html', role: '', write: '', sched: '`:*:*/20' }, { name: 'MSFT.[*]', type: 'web', source: 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=MSFT&apikey=demo', regexp: '[1:2][0:1]', conv: 'json', role: 'number', write: '', sched: '19:10:10' }, { name: 'System.[Mem_used, Mem_free, Swap_used]', type: 'info', source: 'mem', regexp: '[used,free,swapused]', conv: 'parseInt(@*(1000/1024/1024))/1000', role: 'number\|MB', write: '', sched: '*:/1' }, { name: 'System.Software.[*]', type: 'info', source: 'osInfo', regexp: '', conv: '', role: 'string', write: '', sched: '*/3:58' }, { name: 'System.Software.[*]', type: 'info', source: 'versions', regexp: '', conv: '', role: 'string', write: '', sched: '*/3:58' }, { name: 'System.FileSystem.[fs/use]', type: 'info', source: 'fsSize', regexp: '*', conv: '', role: 'number\|%', write: '', sched: '*/3:58' }, { name: 'System.FileSystem.IO_[Read,Write]', type: 'info', source: 'fsStats', regexp: '[rx,wx]', conv: 'parseInt(@*(1000/1024/1024))/1000', role: 'number\|MB', write: '', sched: '*:/1' }, { name: 'System.Network.[iface/]', type: 'info', source: 'networkInterfaces', regexp: '*', conv: '', role: '', write: '', sched: '*/3:58' }, { name: 'System.Network.Connections.[name/value]', type: 'info', source: 'networkConnections', regexp: "[*][!(@.localaddress == @.peeraddress ? null : {name:`${@.protocol}:${@.localaddress.replace(/\\./g,'_')}:${@.localport}`, value:`${@.state}:${@.peeraddress}:${@.peerport}`})]", conv: '', role: 'string', write: '', sched: '*:/1' }, { name: 'System.Network.MB_[Received,Sent]', type: 'info', source: 'networkStats', regexp: '[rx,tx]', conv: 'parseInt(@*(1000/1024/1024))/1000', role: 'number\|MB', write: '', sched: '*:/1' }, { name: 'System.Network.FritzBox.[*]', type: 'info', source: 'inetChecksite("http://fritz.box")', regexp: '', conv: '', role: '', write: '', sched: '*:/1' }, { name: 'System.Network.Latency', type: 'info', source: 'inetLatency', regexp: '', conv: '', role: 'number\|ms', write: '', sched: '*:/1' }, { name: 'System.Load.[Load,User,System,Idle]', type: 'info', source: 'currentLoad', regexp: '[currentload, currentload_user, currentload_system, currentload_idle]', conv: 'parseInt(@*1000)/1000', role: 'number\|ms', write: '', sched: '*:*:/10' }, { name: 'Aussentemp', type: 'file', source: '/mnt/RAM/T_aussen.txt', regexp: '', conv: 'number', role: '', write: '', sched: '* * * * *' } ], lang: 'de', latitude: 52.94304, longitude: 9.09719}
systeminfo.1 | 2023-10-01 16:05:35.292 | info | starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.systeminfo, node: v18.18.0, js-controller: 5.0.12

**Comment by xdaamg** [comment]
Tested version 1.0.0 and 1.1.0. Installation of 0.3.0 was not even possible due to errors. No objects are created under systeminfo, but debug logfile contains information that there are valid results. Error in logfile: "err from getObjectList: TypeError: Cannot read private member from an object whose class did not declare it". 

Loglevel info:
`<html><body>


systeminfo.0 | 2023-10-26 15:39:28.114 | warn | Unhandled error in main: TypeError: Cannot read private member from an object whose class did not declare it
-- | -- | -- | --
systeminfo.0 | 2023-10-26 15:39:20.374 | info | Startup  Systeminfo Adapter systeminfo.0: {  startup: '',  items: [    {       name: 'System.Temperature',      type: 'file',      source:  '/sys/class/thermal/thermal_zone0/temp',      regexp: '',      conv:  'number',      role: 'value.temperature\|°C',      write: '',      sched:  '*:/2'    },    {      name: '-System.Memory_[used, free, available]',       type: 'exec',      source: 'free -k',      regexp:  'Mem\\:\\s+\\d+\\s+(\\d+)\\s+(\\d+)\\s+\\d+\\s+\\d+\\s+(\\d+)',       conv: '@/1000',      role: 'number\|MB',      write: '',      sched: '1 *  * * * '    },    {      name: 'NAS.Space_[total, used, free]',       type: 'exec',      source: 'df -BK',      regexp:  '/lic\\s+(\\d+)K\\s+(\\d+)K\\s+(\\d+)/m',      conv:  'parseInt(@*1000/1024)/1000',      role: 'number\|MB',      write: '',       sched: '1 * * * * '    },    {      name:  '-TestSystem.processes.[command/pcpu]',      type: 'info',      source:  'processes',      regexp: "list[?(@.user == 'pi')]",      conv: '',       role: '',      write: '',      sched: '*:2'    },    {      name:  'System.[Mem_used, Mem_free, Swap_used]',      type: 'info',       source: 'mem',      regexp: '[used,free,swapused]',      conv:  'parseInt(@*(1000/1024/1024))/1000',      role: 'number\|MB',      write:  '',      sched: '*:/1'    },    {      name: 'System.Software.[*]',       type: 'info',      source: 'osInfo',      regexp: '',      conv: '',       role: 'string',      write: '',      sched: '*/3:58'    },    {       name: 'System.Software.[*]',      type: 'info',      source:  'versions',      regexp: '',      conv: '',      role: 'string',       write: '',      sched: '*/3:58'    },    {      name:  'System.FileSystem.[fs/use]',      type: 'info',      source: 'fsSize',       regexp: '*',      conv: '',      role: 'number\|%',      write: '',       sched: '*/3:58'    },    {      name:  'System.FileSystem.IO_[Read,Write]',      type: 'info',      source:  'fsStats',      regexp: '[rx,wx]',      conv:  'parseInt(@*(1000/1024/1024))/1000',      role: 'number\|MB',      write:  '',      sched: '*:/1'    },    {      name: 'System.Network.[iface/]',       type: 'info',      source: 'networkInterfaces',      regexp: '*',       conv: '',      role: '',      write: '',      sched: '*/3:58'    },     {      name: 'System.Network.Connections.[name/value]',      type:  'info',      source: 'networkConnections',      regexp:  "[*][!(@.localaddress == @.peeraddress ? null :   {name:`${@.protocol}:${@.localaddress.replace(/\\./g,'_')}:${@.localport}`,  value:`${@.state}:${@.peeraddress}:${@.peerport}`})]",      conv: '',       role: 'string',      write: '',      sched: '*:/1'    },    {       name: 'System.Network.MB_[Received,Sent]',      type: 'info',       source: 'networkStats',      regexp: '[rx,tx]',      conv:  'parseInt(@*(1000/1024/1024))/1000',      role: 'number\|MB',      write:  '',      sched: '*:/1'    },    {      name:  'System.Network.FritzBox.[*]',      type: 'info',      source:  'inetChecksite("http://192.168.1.1")',      regexp: '',      conv: '',       role: '',      write: '',      sched: '*:/1'    },    {      name:  'System.Network.Latency',      type: 'info',      source: 'inetLatency',       regexp: '',      conv: '',      role: 'number\|ms',      write: '',       sched: '*:/1'    },    {      name:  'System.Load.[Load,User,System,Idle]',      type: 'info',      source:  'currentLoad',      regexp: '[currentload, currentload_user,  currentload_system, currentload_idle]',      conv:  'parseInt(@*1000)/1000',      role: 'number\|ms',      write: '',       sched: '*:*:/10'    }  ]}
systeminfo.0 | 2023-10-26 15:39:20.351 | error | err from getObjectList: TypeError: Cannot read private member from an object whose class did not declare it
systeminfo.0 | 2023-10-26 15:39:20.297 | info | starting. Version 1.1.0 in /opt/iobroker/node_modules/iobroker.systeminfo, node: v18.17.1, js-controller: 5.0.14
systeminfo.0 | 2023-10-26 15:39:14.625 | info | terminating


</body>
</html>`

Example of debug logfile:
`<html><body>


ysteminfo.0 | 2023-10-26 15:45:45.764 | warn | Unhandled error in main: TypeError: Cannot read private member from an object whose class did not declare it
-- | -- | -- | --



</body>
</html>
<html><body>


systeminfo.0 | 2023-10-26 15:45:38.063 | debug | System.Temperature  received '50114'
-- | -- | -- | --
systeminfo.0 | 2023-10-26 15:45:38.010 | debug | TypeError [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received ''


</body>
</html>
<html><body>


systeminfo.0 | 2023-10-26 15:45:43.658 | debug | System.Network.MB_[Received,Sent]   received [  {    iface: 'eth0',    operstate: 'up',    rx_bytes:  1769097207,    rx_dropped: 0,    rx_errors: 0,    tx_bytes: 1157809532,     tx_dropped: 0,    tx_errors: 0,    rx_sec: null,    tx_sec: null,     ms: 0  }]
-- | -- | -- | --
systeminfo.0 | 2023-10-26 15:45:43.594 | debug | MS  TypeError: this._extendObject is not a function    at  MyAdapter.extendObject  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:2068:21)     at  /opt/iobroker/node_modules/iobroker.systeminfo/myAdapter.js:431:96    at  new Promise (<anonymous>)    at MyAdapter.extendObject  (/opt/iobroker/node_modules/iobroker.systeminfo/myAdapter.js:430:20)     at MyAdapter.makeState  (/opt/iobroker/node_modules/iobroker.systeminfo/myAdapter.js:667:21)     at setItem  (/opt/iobroker/node_modules/iobroker.systeminfo/systeminfo.js:467:14)     at /opt/iobroker/node_modules/iobroker.systeminfo/systeminfo.js:595:36     at process.processTicksAndRejections  (node:internal/process/task_queues:95:5)


</body>
</html>`

**Comment by capitaenz** [comment]
same error
